NodeOUs:
  Enable: true
  ClientOUIdentifier:  { OrganizationalUnitIdentifier: client,  Certificate: cacerts/investor-ca-hlf-ca-svc-cluster-local-7054.pem }
  PeerOUIdentifier:    { OrganizationalUnitIdentifier: peer,    Certificate: cacerts/investor-ca-hlf-ca-svc-cluster-local-7054.pem }
  AdminOUIdentifier:   { OrganizationalUnitIdentifier: admin,   Certificate: cacerts/investor-ca-hlf-ca-svc-cluster-local-7054.pem }
  OrdererOUIdentifier: { OrganizationalUnitIdentifier: orderer, Certificate: cacerts/investor-ca-hlf-ca-svc-cluster-local-7054.pem }
