apiVersion: v1
data:
  orderer.yaml: |
    ChannelParticipation:
      Enabled: true
    Consensus:
      SnapDir: /var/hyperledger/production/orderer/etcdraft/snapshot
      WALDir: /var/hyperledger/production/orderer/etcdraft/wal
    FileLedger:
      Location: /var/hyperledger/production/orderer
    General:
      Cluster:
        ListenPort: 7051
      Keepalive:
        ServerMinInterval: 60s
      ListenAddress: 0.0.0.0
      ListenPort: 7050
      TLS:
        Enabled: true
    Metrics:
      Provider: prometheus
    Operations:
      ListenAddress: 0.0.0.0:9443
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"orderer.yaml":"ChannelParticipation:\n  Enabled: true\nConsensus:\n  SnapDir: /var/hyperledger/production/orderer/etcdraft/snapshot\n  WALDir: /var/hyperledger/production/orderer/etcdraft/wal\nFileLedger:\n  Location: /var/hyperledger/production/orderer\nGeneral:\n  Cluster:\n    ListenPort: 7051\n  Keepalive:\n    ServerMinInterval: 60s\n  ListenAddress: 0.0.0.0\n  ListenPort: 7050\n  TLS:\n    Enabled: true\nMetrics:\n  Provider: prometheus\nOperations:\n  ListenAddress: 0.0.0.0:9443\n"},"kind":"ConfigMap","metadata":{"annotations":{},"creationTimestamp":null,"name":"fabric-orderer-config","namespace":"hlf-orderer"}}
    meta.helm.sh/release-name: fabric-orderer
    meta.helm.sh/release-namespace: hlf-orderer
  creationTimestamp: "2025-08-08T22:55:32Z"
  labels:
    app.kubernetes.io/instance: fabric-orderer
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: fabric-orderer
    helm.sh/chart: fabric-orderer-0.1.0
  name: fabric-orderer-config
  namespace: hlf-orderer
  resourceVersion: "876745791"
  uid: 21722b74-daa6-4809-b957-1436d52241cb
