{{- $ns := .Values.namespace -}}
{{- range .Values.peers }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
  namespace: {{ $ns }}
  labels:
    app: {{ .name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .name }}
  ports:
    - name: peer
      port: {{ $.Values.ports.listen }}
      targetPort: {{ $.Values.ports.listen }}
    - name: chaincode
      port: {{ $.Values.ports.chaincode }}
      targetPort: {{ $.Values.ports.chaincode }}
    - name: ops
      port: {{ $.Values.ports.operations }}
      targetPort: {{ $.Values.ports.operations }}
---
{{- end }}
