NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/greenstand-ca.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/greenstand-ca.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/greenstand-ca.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/greenstand-ca.pem
    OrganizationalUnitIdentifier: orderer
